### PR TITLE
Backport raw headers fix to 0.28

### PR DESCRIPTION
**Pull request by abhinav**
This backports Yuri's change from #443 to the 0.28 release.

CC @yurishkuro @breerly @blampe

### CODE REVIEW

**Comment by yurishkuro** [comment]
:shipit: 

thanks!

**Comment by breerly** [comment]
:shipit:

**Comment by breerly** [comment]
Curious - why backport this fix at all? Do we have customers that can't upgrade to the latest minor?

**Comment by abhinav** [comment]
We haven't released 0.29 yet. We will probably do that soon but backporting it allows us to not worry about whether people have upgraded. Also, at least one customer wants to make use of the new API being introduced in 0.29, which means they'll probably need a little time to upgrade.

**Pull request merged**
