### PR TITLE
Calls should reraise with the origianl traceback when retries run out

### PR DESCRIPTION
**Pull request by abhinav**
`raise error` eliminates the stack trace from the original failure.

This is being merged into the queue-terminate branch rather than master.

### CODE REVIEW

**Comment by abhinav** [comment]
@blampe @breerly @junchaowu

**Comment by blampe** [comment]
> This is being merged into the queue-terminate branch rather than master.

Why not patch on master?

**Comment by abhinav** [comment]
I'll cherry pick it on master but I want this change on the queue-terminate branch because we have some people test driving that branch right now.

**Comment by blampe** [comment]
Gotcha sounds good! :ship:

**Pull request merged**
