### PR TITLE
Update OpenTracing instrumentation package

### PR DESCRIPTION
**Pull request by isaachier**

### CODE REVIEW

**Comment by abhinav** [comment]
Sorry, I don't see how this will fix an issue. The original version bound is
broad enough that 2.4 will be picked up by the tooling. You're likely getting
the older version from a different dependency. I think you can run `pip` with
three `-v`s to get super-verbose output. That may tell you why it's picking up
the old version.

**Comment by isaachier** [comment]
Fair enough. Not really sure what was going on in my build but it seemed to grep for identical versions of instrumentation and fail there. Will update soon. Thanks.

**Comment by abhinav** [comment]
https://github.com/naiquevin/pipdeptree may prove useful in debugging this

**Comment by isaachier** [comment]
OK seems I picked the wrong package. Sorry for the confusion. Thanks again!

**Comment by isaachier** [comment]
Awesome. Actually turned out to be a tox issue. Pinned version of OT instrumentation was wrong there. Sorry for the hassle.

**Pull request closed without merging**
