### PR TITLE
WIP - 2.0

### PR DESCRIPTION
**Pull request by abhinav**
## Removing Deprecated Functionality
- [x] remove `client_for` - #259 
- [x] remove `thrift_request_builder` - #264 
- [ ] update migration guide to move users to `thrift.load`
- [ ] ensure all breaking changes are documented in the migration guide
- [ ] remove `tchannel.tornado.TChannel.register`
## Remove Apache Thrift Support
- [x] remove `testing.data.generated` - #265 
- [x] update tests to not test apache thrift
- [x] Delete `ThriftRequest` in favor of `ThriftRWRequest` (possibly rename the latter)
- [x] Delete `ThriftSerializer` in favor of `ThriftRWSerializer` (possibly rename the latter)
- [x] Delete Apache Thrift endpoint registration code. 
- [x] lint config should not consider generated code #274
- [x] Add "Removing Apache Thrift Support" to the top of the changelog. - #275
## New Functionality
- [ ] public event api (use new req/res objs, resp timer, content size)
- [ ] mocking test helpers (we already have a recorder for integration tests)
- [ ] customizable request context (#145, #143)
- [ ] `TChannel.register` should just be "raw" endpoints (not `as: raw`) that receive the raw bytes, parse them manually as required, and return raw bytes in the Response. We should be able to refactor `TChannel.{thrift,raw,json}.register` to wrap around this.
- [x] enable unit testing endpoints by calling the functions directly - #302
## Performance
- [ ] fix event hooks not firing immediately #285
## In Preperation for 2.0
- [ ] remove argstreams

### CODE REVIEW

**Comment by blampe** [comment]
There's some good stuff sitting on this branch like peer selection, thriftrw, lint etc. that we probably want to release. I'm wondering if we can split out the backwards-breaking changes and release those separately.

**Comment by breerly** [comment]
Agreed.

Although it's probably worth considering biting the bullet and just releasing the whole, considering the previous minor contains both APIs before we removed deprecated ones.

**Comment by blampe** [comment]
I really want to avoid breaking changes so I'd rather we just pull out the stuff that's patch-worthy.

**Comment by breerly** [comment]
@abhinav @junchaowu @blampe are you guys opposed to renaming this "WIP 1.0 release"?

**Comment by abhinav** [comment]
:+1:

**Comment by breerly** [comment]
@abhinav can you remove the items from the description that have already been merged to master?

**Comment by abhinav** [comment]
done

**Comment by abhinav** [comment]
RIP

**Pull request closed without merging**
