### PR TITLE
json headers are map[string]string

### LINKED ISSUE #117: Json headers should only accept map[string]=string
And should `ValueError` otherwise, just like with out Thrift implementation.

### PR DESCRIPTION
**Pull request by blampe**
Quick hack, will fix the inheritance tomorrow. Resolves #117.

@breerly @junchaowu

### CODE REVIEW

**Comment by blampe** [comment]
Note this is landing in 0.18.

**Comment by breerly** [comment]
This is a bug right - we should patch 0.17

**Comment by blampe** [comment]
backwards incompat

**Comment by breerly** [comment]
you passed the test.

:shipit:

**Comment by junchaowu** [comment]
lgtm

**Comment by abhinav** [comment]
Does this also change the behavior for call headers (for outgoing requests)? The changelog just mentions response headers.

**Comment by breerly** [comment]
:shipit: ?

**Comment by abhinav** [comment]
Can't ship. Need to resolve conflicts.

**Pull request merged**
