### PR TITLE
reduce zipkin failures to warnings

### PR DESCRIPTION
**Pull request by blampe**
@junchaowu @abhinav @breerly

### CODE REVIEW

**Comment by abhinav** [comment]
It makes sense to still include the trace even if you lower this to warn/info. We want to know what exactly went wrong when the failure does occur.

**Comment by breerly** [comment]
This is a good change. :+1: 

Also, seems like this should go in the 0.19 branch, since it's not fixing a bug.

**Comment by blampe** [comment]
Sure, will land on 0.19.

**Comment by blampe** [comment]
Landing in #273.

**Pull request closed without merging**
