### PR TITLE
Reduce advertise interval frequency to once every 3 minutes

### PR DESCRIPTION
**Pull request by blampe**
@Raynos @abhinav

### CODE REVIEW

**Comment by abhinav** [comment]
More context? Why?

**Comment by blampe** [comment]
This is something Jake suggested to take some load off of HB.

**Comment by breerly** [comment]
Doesn't HB prune services in less than 3 mins? Or do they never actually fall off?

**Comment by junchaowu** [comment]
3 minutes . that's a long time.

**Comment by junchaowu** [comment]
Probably change the title from reduce to increase.

**Comment by blampe** [comment]
@breerly @Raynos is going to coordinate a separate change for HB to go along with this.

**Comment by Raynos** [comment]
@breerly the pruner runs every 5 mins; so thats a 1:5 ratio atm, ill change it to 9 minutes, which means we reduce to a 3:9 ratio.

**Comment by abhinav** [comment]
:ok:

**Pull request merged**
