### PR TITLE
reduce default sample rate

### LINKED ISSUE #364: Change default sampling rate for tracing to 1%
The current default sampling rate of 100% is unheard of in distributed tracing. If deployed in a high-throughput service it can easily DDOS the tracing system.

https://github.com/uber/tchannel-python/blob/master/tchannel/zipkin/zipkin_trace.py#L32
```python
    DEFAULT_RATE = 1.0
```

### PR DESCRIPTION
**Pull request by blampe**
Resolves #364.

@abhinav @junchaowu

### CODE REVIEW

**Comment by junchaowu** [comment]
lgtm

**Comment by abhinav** [comment]
:ok:

**Comment by abhinav** [comment]
Rebased on master.

**Comment by breerly** [comment]
:shipit: (obv not a patch but :shrug:)

**Pull request merged**
