### PR TITLE
WIP - Crossdock tests on OpenTracing API 1.1

### PR DESCRIPTION
**Pull request by yurishkuro**

### CODE REVIEW

**Comment by breerly** [comment]
You might think about library-izing the Python stuff, we'd be happy to start something at github.com/crossdock/crossdock-python to make writing Crossdock test suites easy.

**Comment by breerly** [comment]
Of course, we'll eventually get to the Python client if you aren't interested in starting it :)

**Comment by yurishkuro** [comment]
@breerly I did not need crossdock client in Python, just the server implementations. Did a bit of manual permutations in the [unit test though](https://github.com/uber/tchannel-python/pull/424/files#diff-e33e43889da04c7c927f57a2ae8059a4R74)

**Comment by breerly** [comment]
👍

**Pull request closed without merging**
