### PR TITLE
constraint to tornado 4.3

### PR DESCRIPTION
**Pull request by breerly**
@abhinav @blampe @junchaowu

### CODE REVIEW

**Comment by abhinav** [comment]
ok

**Comment by thecadams** [comment]
thanks so much for the quick response here.

**Comment by breerly** [comment]
@thecadams no problem - it's a bummer that pip doesn't respect version library-declared version constraints. I think we'll probably end up in a place where we do a hard fail.

**Comment by abhinav** [comment]
LGTM

**Pull request merged**
