### PR TITLE
vendor tornado's bind_socket for port re-use

### PR DESCRIPTION
**Pull request by blampe**
I'll re-run tests a few time to see if this fixes the issue.

@abhinav @breerly @junchaowu

### CODE REVIEW

**Comment by junchaowu** [comment]
what problem do you see with bind_socket?

**Comment by abhinav** [comment]
:+1:

**Comment by junchaowu** [comment]
I doubt it will work. After reading this: http://stackoverflow.com/questions/14388706/socket-options-so-reuseaddr-and-so-reuseport-how-do-they-differ-do-they-mean-t

**Comment by blampe** [comment]
Not seeing in-use errors but still getting timeouts. Giving up on this approach for now.

**Pull request closed without merging**
