### PR TITLE
change peer selection strategy to prefer incoming conn over outgoing conn

### PR DESCRIPTION
**Pull request by junchaowu**
@abhinav @blampe @breerly @ShanniLi

### CODE REVIEW

**Comment by breerly** [comment]
Trying to patch `0.17`? Let's update the CHANGELOG if so.

**Comment by junchaowu** [comment]
this is a bugfix and internally.

**Comment by abhinav** [comment]
Regarding changelog: Invisible to the user usually means renaming internal APIs or changing minor internal behavior that doesn't affect anything outside. This change actually affects the user: It fixes a bug which was causing invalid behavior. Consider adding a changelog entry similar to:

* Fixed a bug which caused incoming connections for certain peers to be ignored in favor of outgoing connections.

Also, this change doesn't really fix the problem. Now, we'll just always use the same incoming connection. How about cycling through all connections for a peer instead?

**Comment by ShanniLi** [comment]
@abhinav It is OK to always use one connection. Actual, there will only be one in-connection from Hyperbahn for client to use.

The idea of this PR is choosing the right peer (i.e., Hyperbahn node) for requests.

**Comment by abhinav** [comment]
This PR doesn't change the peer selection logic at all. It changes how multiple connections for a single peer are treated.

**Comment by junchaowu** [comment]
After discuss with juncaoli, this PR will depend on https://github.com/uber/tchannel-python/pull/190 .

**Comment by breerly** [comment]
@junchaowu why is this blocked by that refactor?

**Comment by junchaowu** [comment]
basically to calculate a health weight of a peer depending on some factors like pending requests/response in that peer, number of connections. The pending requests/responses will be part of that PR

**Comment by junchaowu** [comment]
doesn't apply anymore.

**Pull request closed without merging**
