### PR TITLE
Hide more internal details for thriftrw

### PR DESCRIPTION
**Pull request by abhinav**
These should never be accessed directly.

@blampe @breerly @junchaowu

### CODE REVIEW

**Comment by breerly** [comment]
Hard to argue with that :clap:

**Comment by breerly** [comment]
:ship:

**Comment by blampe** [comment]
Worth mentioning in the upgrade guide in case anyone was crazy enough to find this already. Otherwise LGTM

**Comment by abhinav** [comment]
Updated

**Pull request merged**
