### PR TITLE
remove explicit dep on futures

### PR DESCRIPTION
**Pull request by breerly**
we already get futures implicitly through threadloop

### CODE REVIEW

**Comment by abhinav** [comment]
:+1: 

We don't ever directly use the `concurrent.futures` module in our code base.

**Comment by breerly** [comment]
@abhinav wow - looks like we found a bug in threadloop - nice!

**Comment by breerly** [comment]
hmmm... the issue actually appears to be in tox. I'm going to create a workaround that still accomplishes the goal of this PR and add a detailed comment.

**Comment by junchaowu** [comment]
lgtm

**Comment by abhinav** [comment]
:+1:

**Pull request merged**
