### PR TITLE
add testing for streaming examples

### PR DESCRIPTION
**Pull request by blampe**
The API is broken right now but this asserts bytes can still be sent over the wire.

@abhinav @breerly @junchaowu

### CODE REVIEW

**Comment by abhinav** [comment]
I thoughts streaming was broken?

**Comment by blampe** [comment]
The API can pass bytes around but doesn't currently allow the use cases we're interested in (we don't get a chunk "streamed" to us until it fills up).

**Comment by abhinav** [comment]
In that case I don't see what this test adds, but :ok:.

**Comment by blampe** [comment]
We're going to be refactoring this stuff significantly and I want to make sure our examples stay relevant/working.

**Pull request merged**
