### PR TITLE
Test that we work with both, Tornado 4.2 and 4.3

### PR DESCRIPTION
**Pull request by abhinav**
This tests that the library continues to work even if used with Tornado 4.2

Depends on https://github.com/uber/tchannel-python/pull/409

### CODE REVIEW

**Comment by abhinav** [comment]
CC @blampe @breerly @junchaowu

**Comment by blampe** [comment]
ok

**Comment by breerly** [comment]
:shipit: when tests pass.

I'm think I'm going to whip up a lib called `install-actually-requires` that reads all the version constrains in `install_requires` and raises exceptions if they are not *actually* satisfied.

**Comment by breerly** [comment]
I've seen this fail a handful of times since yesterday:

```
______________ ERROR at teardown of test_protocol_error[hostPort] ______________
cassette = <InstanceDouble of <class 'tchannel.testing.vcr.cassette.Cassette'> object at 0x2acc824d6e50>
unpatch = <function reset at 0x2acc833248c0>
    @pytest.yield_fixture
    def vcr_service(cassette, unpatch):
        with VCRProxyService(cassette, unpatch) as vcr_service:
>           yield vcr_service
tests/testing/vcr/test_server.py:65: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tchannel/testing/vcr/server.py:219: in __exit__
    self.stop()
tchannel/testing/vcr/server.py:205: in stop
    self.tchannel._dep_tchannel.close()
tchannel/tornado/tchannel.py:206: in close
    self.peers.clear()
tchannel/tornado/peer.py:607: in clear
    peer.close()
tchannel/tornado/peer.py:248: in close
    connection.close()
tchannel/tornado/connection.py:313: in close
    self.connection.close()
.tox/py27-tornado42/lib/python2.7/site-packages/tornado/iostream.py:436: in close
    self.close_fd()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <tornado.iostream.IOStream object at 0x2acc834d1ed0>
    def close_fd(self):
>       self.socket.close()
E       AttributeError: 'NoneType' object has no attribute 'close'
```

Have you guys seen this before? Makes me wonder if its from `SO_REUSEPORT` or just from a flaky test.

**Pull request merged**
